[book]
authors = ["johannst"]
language = "en"
multilingual = false
src = "src"
title = "Cookbook"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/johannst/cookbook"
git-repository-icon = "fa-github"
